const express = require('express');
const router = express.Router();
const suppliersController = require('./suppliers.controller');
const { verifyToken } = require('../../core/middleware/auth');
const { moduleCheck } = require('../../core/middleware/moduleCheck');
const { handlerWithFields } = require('../../core/utils/zodTypeView');
const validate = require('../../core/middleware/validate');
const { createSupplier, updateSupplier } = require('./suppliers.validation');

// Module name for routes-tree grouping
router.moduleName = 'Suppliers';

router.use(verifyToken);
router.use(moduleCheck('suppliers'));

// Define routes metadata with comprehensive documentation
router.routesMeta = [
    {
        path: '/',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => suppliersController.getAllSuppliers(req, res),
        description: 'Get all suppliers with pagination',
        database: {
            tables: ['suppliers', 'purchase_orders', 'purchase_payments'],
            mainTable: 'suppliers',
            fields: {
                suppliers: ['id', 'name', 'code', 'contact_person', 'email', 'phone', 'address', 'city', 'state', 'country', 'postal_code', 'latitude', 'longitude', 'tax_id', 'website', 'payment_terms', 'notes', 'thumb_url', 'gallery_items', 'is_active', 'created_at', 'updated_at'],
                calculated: ['total_purchase_amount', 'total_paid_amount', 'total_due_amount']
            }
        },
        queryParams: {
            page: 'Page number (default: 1)',
            limit: 'Items per page (default: 10)',
            is_active: 'Filter by active status (true/false)',
            search: 'Search by name, code, email, or contact person'
        },
        sampleResponse: {
            success: true,
            message: 'Suppliers retrieved successfully',
            pagination: {
                total: 5,
                page: '1',
                limit: '10',
                totalPage: 1
            },
            data: [
                {
                    id: 1,
                    name: 'Tech Supplies Inc',
                    code: 'SUP-001',
                    contact_person: 'John Smith',
                    email: 'john@techsupplies.com',
                    phone: '+1234567890',
                    is_active: true,
                    total_purchase_amount: 50000.00,
                    total_paid_amount: 45000.00,
                    total_due_amount: 5000.00,
                    created_at: '2025-12-03T05:00:00.000Z'
                }
            ]
        },
        examples: [
            {
                title: 'List Suppliers',
                description: 'Retrieve a paginated list of suppliers.',
                url: '/api/suppliers?page=1&limit=10&is_active=true',
                method: 'GET',
                response: {
                    success: true,
                    message: 'Suppliers retrieved successfully',
                    pagination: { total: 5, page: '1', limit: '10', totalPage: 1 },
                    data: [{ id: 1, name: 'Tech Supplies Inc', code: 'SUP-001' }]
                }
            }
        ]
    },
    {
        path: '/',
        method: 'POST',
        middlewares: [validate(createSupplier)],
        handler: handlerWithFields((req, res) => suppliersController.createSupplier(req, res), createSupplier),
        description: 'Add a new supplier',
        database: {
            tables: ['suppliers'],
            mainTable: 'suppliers',
            requiredFields: ['name'],
            optionalFields: ['code', 'contact_person', 'email', 'phone', 'address', 'city', 'state', 'country', 'postal_code', 'latitude', 'longitude', 'tax_id', 'website', 'payment_terms', 'notes', 'thumb_url', 'gallery_items', 'is_active'],
            autoGeneratedFields: ['id', 'created_at', 'updated_at']
        },
        sampleRequest: {
            name: 'Office Supplies Co',
            code: 'SUP-002',
            contact_person: 'Bob Smith',
            email: 'bob@officesupplies.com',
            phone: '+1987654321',
            address: '456 Market St',
            city: 'Chicago',
            country: 'USA',
            payment_terms: 'Net 30',
            thumb_url: 'https://example.com/logo.png',
            gallery_items: [{ "url": "https://example.com/img1.png", "caption": "Office" }],
            is_active: true
        },
        sampleResponse: {
            status: true,
            message: 'Supplier created successfully',
            data: {
                id: 2,
                name: 'Office Supplies Co',
                email: 'bob@officesupplies.com',
                created_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Create Supplier',
                description: 'Add a new supplier to the system.',
                url: '/api/suppliers',
                method: 'POST',
                request: {
                    name: 'Office Supplies Co',
                    code: 'SUP-002',
                    contact_person: 'Bob Smith',
                    email: 'bob@officesupplies.com',
                    payment_terms: 'Net 30'
                },
                response: {
                    status: true,
                    message: 'Supplier created successfully',
                    data: { id: 2, name: 'Office Supplies Co' }
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'GET',
        middlewares: [],
        handler: (req, res) => suppliersController.getSupplierById(req, res),
        description: 'Get supplier details',
        database: {
            tables: ['suppliers'],
            mainTable: 'suppliers',
            fields: {
                suppliers: ['id', 'name', 'code', 'contact_person', 'email', 'phone', 'address', 'city', 'state', 'country', 'postal_code', 'latitude', 'longitude', 'tax_id', 'website', 'payment_terms', 'notes', 'thumb_url', 'gallery_items', 'is_active', 'created_at', 'updated_at']
            }
        },
        sampleResponse: {
            status: true,
            data: {
                id: 1,
                name: 'Global Electronics Ltd',
                code: 'SUP-003',
                contact_person: 'Alice Johnson',
                email: 'alice@globalelectronics.com',
                phone: '+1234567890',
                address: '789 Tech Park',
                city: 'San Jose',
                country: 'USA',
                payment_terms: 'Net 60',
                is_active: true,
                created_at: '2025-12-02T10:00:00.000Z',
                updated_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Get Supplier',
                description: 'Retrieve detailed information about a specific supplier.',
                url: '/api/suppliers/1',
                method: 'GET',
                response: {
                    status: true,
                    data: { id: 1, name: 'Global Electronics Ltd', contact_person: 'Alice Johnson' }
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'PUT',
        middlewares: [validate(updateSupplier)],
        handler: handlerWithFields((req, res) => suppliersController.updateSupplier(req, res), updateSupplier),
        description: 'Update a supplier',
        database: {
            tables: ['suppliers'],
            mainTable: 'suppliers',
            updatableFields: ['name', 'code', 'contact_person', 'email', 'phone', 'address', 'city', 'state', 'country', 'postal_code', 'latitude', 'longitude', 'tax_id', 'website', 'payment_terms', 'notes', 'thumb_url', 'gallery_items', 'is_active'],
            readOnlyFields: ['id', 'created_at'],
            autoUpdatedFields: ['updated_at']
        },
        sampleRequest: {
            name: 'Global Electronics Inc',
            contact_person: 'Alice Smith',
            payment_terms: 'Net 45',
            thumb_url: 'https://example.com/new-logo.png'
        },
        sampleResponse: {
            status: true,
            message: 'Supplier updated successfully',
            data: {
                id: 1,
                name: 'Global Electronics Inc',
                updated_at: '2025-12-02T10:00:00.000Z'
            }
        },
        examples: [
            {
                title: 'Update Supplier',
                description: 'Update the details of an existing supplier.',
                url: '/api/suppliers/1',
                method: 'PUT',
                request: { name: 'Global Electronics Inc', contact_person: 'Alice Smith' },
                response: {
                    status: true,
                    message: 'Supplier updated successfully',
                    data: { id: 1, name: 'Global Electronics Inc' }
                }
            }
        ]
    },
    {
        path: '/:id',
        method: 'DELETE',
        middlewares: [],
        handler: (req, res) => suppliersController.deleteSupplier(req, res),
        description: 'Delete a supplier',
        database: {
            tables: ['suppliers', 'purchase_orders'],
            mainTable: 'suppliers',
            sideEffects: ['May affect existing purchase_orders - check foreign key constraints']
        },
        sampleResponse: {
            status: true,
            message: 'Supplier deleted successfully'
        },
        examples: [
            {
                title: 'Delete Supplier',
                description: 'Remove a supplier from the system.',
                url: '/api/suppliers/1',
                method: 'DELETE',
                response: {
                    status: true,
                    message: 'Supplier deleted successfully'
                }
            }
        ]
    }
];

// Register routes from metadata
router.routesMeta.forEach(r => {
    router[r.method.toLowerCase()](r.path, ...r.middlewares, r.handler);
});

module.exports = router;
