/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTestsIndexRouteImport } from './routes/_authenticated/tests/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDueCollectionIndexRouteImport } from './routes/_authenticated/due-collection/index'
import { Route as AuthenticatedDoctorsIndexRouteImport } from './routes/_authenticated/doctors/index'
import { Route as AuthenticatedDepartmentsIndexRouteImport } from './routes/_authenticated/departments/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedXRayAllReportsIndexRouteImport } from './routes/_authenticated/x-ray/all-reports/index'
import { Route as AuthenticatedUltrasonogramAllReportsIndexRouteImport } from './routes/_authenticated/ultrasonogram/all-reports/index'
import { Route as AuthenticatedTestsCreateIndexRouteImport } from './routes/_authenticated/tests/create/index'
import { Route as AuthenticatedInvoicesListIndexRouteImport } from './routes/_authenticated/invoices/list/index'
import { Route as AuthenticatedInvoicesCreateIndexRouteImport } from './routes/_authenticated/invoices/create/index'
import { Route as AuthenticatedEcgAllReportsIndexRouteImport } from './routes/_authenticated/ecg/all-reports/index'
import { Route as AuthenticatedTestsEditIdIndexRouteImport } from './routes/_authenticated/tests/edit/[$id]/index'
import { Route as AuthenticatedPathologyUrineUrineForSugarIndexRouteImport } from './routes/_authenticated/pathology/urine/urine-for-sugar/index'
import { Route as AuthenticatedPathologyUrineUrineForReFullIndexRouteImport } from './routes/_authenticated/pathology/urine/urine-for-re-full/index'
import { Route as AuthenticatedPathologyUrineUrineForAlbuminIndexRouteImport } from './routes/_authenticated/pathology/urine/urine-for-albumin/index'
import { Route as AuthenticatedPathologyStoolStoolReIndexRouteImport } from './routes/_authenticated/pathology/stool/stool-re/index'
import { Route as AuthenticatedPathologyStoolReducingSubstanceIndexRouteImport } from './routes/_authenticated/pathology/stool/reducing-substance/index'
import { Route as AuthenticatedPathologyStoolOcultBloodTestIndexRouteImport } from './routes/_authenticated/pathology/stool/ocult-blood-test/index'
import { Route as AuthenticatedPathologySpecialT3t4tshIndexRouteImport } from './routes/_authenticated/pathology/special/t3t4tsh/index'
import { Route as AuthenticatedPathologySpecialSputumIndexRouteImport } from './routes/_authenticated/pathology/special/sputum/index'
import { Route as AuthenticatedPathologySpecialSkinScrappingForFungusIndexRouteImport } from './routes/_authenticated/pathology/special/skin-scrapping-for-fungus/index'
import { Route as AuthenticatedPathologySpecialSemenIndexRouteImport } from './routes/_authenticated/pathology/special/semen/index'
import { Route as AuthenticatedPathologySpecialElectrolytesIndexRouteImport } from './routes/_authenticated/pathology/special/electrolytes/index'
import { Route as AuthenticatedPathologySpecialAllHormonesIndexRouteImport } from './routes/_authenticated/pathology/special/all-hormones/index'
import { Route as AuthenticatedPathologyImmunologyWidalTestIndexRouteImport } from './routes/_authenticated/pathology/immunology/widal-test/index'
import { Route as AuthenticatedPathologyImmunologyReportsIndexRouteImport } from './routes/_authenticated/pathology/immunology/reports/index'
import { Route as AuthenticatedPathologyImmunologyMtIndexRouteImport } from './routes/_authenticated/pathology/immunology/mt/index'
import { Route as AuthenticatedPathologyImmunologyBloodGroupIndexRouteImport } from './routes/_authenticated/pathology/immunology/blood-group/index'
import { Route as AuthenticatedPathologyImmunologyBetaHcgIndexRouteImport } from './routes/_authenticated/pathology/immunology/beta-hcg/index'
import { Route as AuthenticatedPathologyHematologyReportsIndexRouteImport } from './routes/_authenticated/pathology/hematology/reports/index'
import { Route as AuthenticatedPathologyHematologyProthomBinTimeFullIndexRouteImport } from './routes/_authenticated/pathology/hematology/prothom-bin-time-full/index'
import { Route as AuthenticatedPathologyHematologyPeripheralBloodFilmIndexRouteImport } from './routes/_authenticated/pathology/hematology/peripheral-blood-film/index'
import { Route as AuthenticatedPathologyHematologyCbcShortIndexRouteImport } from './routes/_authenticated/pathology/hematology/cbc-short/index'
import { Route as AuthenticatedPathologyHematologyBloodForTcdcIndexRouteImport } from './routes/_authenticated/pathology/hematology/blood-for-tcdc/index'
import { Route as AuthenticatedPathologyHematologyBloodForBtCtIndexRouteImport } from './routes/_authenticated/pathology/hematology/blood-for-bt-ct/index'
import { Route as AuthenticatedPathologyBiochemicalReportsIndexRouteImport } from './routes/_authenticated/pathology/biochemical/reports/index'
import { Route as AuthenticatedPathologyBiochemicalLipidProfileIndexRouteImport } from './routes/_authenticated/pathology/biochemical/lipid-profile/index'
import { Route as AuthenticatedXRayAllReportsEditIdRouteImport } from './routes/_authenticated/x-ray/all-reports/edit/$id'
import { Route as AuthenticatedUltrasonogramAllReportsEditIdRouteImport } from './routes/_authenticated/ultrasonogram/all-reports/edit/$id'
import { Route as AuthenticatedEcgAllReportsEditIdRouteImport } from './routes/_authenticated/ecg/all-reports/edit/$id'
import { Route as AuthenticatedPathologyUrineUrineForReFullEditIdRouteImport } from './routes/_authenticated/pathology/urine/urine-for-re-full/edit/$id'
import { Route as AuthenticatedPathologyStoolStoolReEditIdRouteImport } from './routes/_authenticated/pathology/stool/stool-re/edit/$id'
import { Route as AuthenticatedPathologySpecialSemenEditReportIdRouteImport } from './routes/_authenticated/pathology/special/semen/edit/$reportId'
import { Route as AuthenticatedPathologyHematologyCbcShortEditIdRouteImport } from './routes/_authenticated/pathology/hematology/cbc-short/edit/$id'
import { Route as AuthenticatedPathologyBiochemicalReportsEditReportIdRouteImport } from './routes/_authenticated/pathology/biochemical/reports/edit/$reportId'
import { Route as AuthenticatedPathologySpecialAllHormonesEditIdIndexRouteImport } from './routes/_authenticated/pathology/special/all-hormones/edit/[$id]/index'
import { Route as AuthenticatedPathologyImmunologyReportsEditIdIndexRouteImport } from './routes/_authenticated/pathology/immunology/reports/edit/[$id]/index'
import { Route as AuthenticatedPathologyHematologyReportsEditIdIndexRouteImport } from './routes/_authenticated/pathology/hematology/reports/edit/[$id]/index'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestsIndexRoute = AuthenticatedTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDueCollectionIndexRoute =
  AuthenticatedDueCollectionIndexRouteImport.update({
    id: '/due-collection/',
    path: '/due-collection/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorsIndexRoute =
  AuthenticatedDoctorsIndexRouteImport.update({
    id: '/doctors/',
    path: '/doctors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepartmentsIndexRoute =
  AuthenticatedDepartmentsIndexRouteImport.update({
    id: '/departments/',
    path: '/departments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedXRayAllReportsIndexRoute =
  AuthenticatedXRayAllReportsIndexRouteImport.update({
    id: '/x-ray/all-reports/',
    path: '/x-ray/all-reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUltrasonogramAllReportsIndexRoute =
  AuthenticatedUltrasonogramAllReportsIndexRouteImport.update({
    id: '/ultrasonogram/all-reports/',
    path: '/ultrasonogram/all-reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsCreateIndexRoute =
  AuthenticatedTestsCreateIndexRouteImport.update({
    id: '/tests/create/',
    path: '/tests/create/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesListIndexRoute =
  AuthenticatedInvoicesListIndexRouteImport.update({
    id: '/invoices/list/',
    path: '/invoices/list/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesCreateIndexRoute =
  AuthenticatedInvoicesCreateIndexRouteImport.update({
    id: '/invoices/create/',
    path: '/invoices/create/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcgAllReportsIndexRoute =
  AuthenticatedEcgAllReportsIndexRouteImport.update({
    id: '/ecg/all-reports/',
    path: '/ecg/all-reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsEditIdIndexRoute =
  AuthenticatedTestsEditIdIndexRouteImport.update({
    id: '/tests/edit/$id/',
    path: '/tests/edit/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyUrineUrineForSugarIndexRoute =
  AuthenticatedPathologyUrineUrineForSugarIndexRouteImport.update({
    id: '/pathology/urine/urine-for-sugar/',
    path: '/pathology/urine/urine-for-sugar/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyUrineUrineForReFullIndexRoute =
  AuthenticatedPathologyUrineUrineForReFullIndexRouteImport.update({
    id: '/pathology/urine/urine-for-re-full/',
    path: '/pathology/urine/urine-for-re-full/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyUrineUrineForAlbuminIndexRoute =
  AuthenticatedPathologyUrineUrineForAlbuminIndexRouteImport.update({
    id: '/pathology/urine/urine-for-albumin/',
    path: '/pathology/urine/urine-for-albumin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyStoolStoolReIndexRoute =
  AuthenticatedPathologyStoolStoolReIndexRouteImport.update({
    id: '/pathology/stool/stool-re/',
    path: '/pathology/stool/stool-re/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyStoolReducingSubstanceIndexRoute =
  AuthenticatedPathologyStoolReducingSubstanceIndexRouteImport.update({
    id: '/pathology/stool/reducing-substance/',
    path: '/pathology/stool/reducing-substance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyStoolOcultBloodTestIndexRoute =
  AuthenticatedPathologyStoolOcultBloodTestIndexRouteImport.update({
    id: '/pathology/stool/ocult-blood-test/',
    path: '/pathology/stool/ocult-blood-test/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologySpecialT3t4tshIndexRoute =
  AuthenticatedPathologySpecialT3t4tshIndexRouteImport.update({
    id: '/pathology/special/t3t4tsh/',
    path: '/pathology/special/t3t4tsh/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologySpecialSputumIndexRoute =
  AuthenticatedPathologySpecialSputumIndexRouteImport.update({
    id: '/pathology/special/sputum/',
    path: '/pathology/special/sputum/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologySpecialSkinScrappingForFungusIndexRoute =
  AuthenticatedPathologySpecialSkinScrappingForFungusIndexRouteImport.update({
    id: '/pathology/special/skin-scrapping-for-fungus/',
    path: '/pathology/special/skin-scrapping-for-fungus/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologySpecialSemenIndexRoute =
  AuthenticatedPathologySpecialSemenIndexRouteImport.update({
    id: '/pathology/special/semen/',
    path: '/pathology/special/semen/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologySpecialElectrolytesIndexRoute =
  AuthenticatedPathologySpecialElectrolytesIndexRouteImport.update({
    id: '/pathology/special/electrolytes/',
    path: '/pathology/special/electrolytes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologySpecialAllHormonesIndexRoute =
  AuthenticatedPathologySpecialAllHormonesIndexRouteImport.update({
    id: '/pathology/special/all-hormones/',
    path: '/pathology/special/all-hormones/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyImmunologyWidalTestIndexRoute =
  AuthenticatedPathologyImmunologyWidalTestIndexRouteImport.update({
    id: '/pathology/immunology/widal-test/',
    path: '/pathology/immunology/widal-test/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyImmunologyReportsIndexRoute =
  AuthenticatedPathologyImmunologyReportsIndexRouteImport.update({
    id: '/pathology/immunology/reports/',
    path: '/pathology/immunology/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyImmunologyMtIndexRoute =
  AuthenticatedPathologyImmunologyMtIndexRouteImport.update({
    id: '/pathology/immunology/mt/',
    path: '/pathology/immunology/mt/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyImmunologyBloodGroupIndexRoute =
  AuthenticatedPathologyImmunologyBloodGroupIndexRouteImport.update({
    id: '/pathology/immunology/blood-group/',
    path: '/pathology/immunology/blood-group/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyImmunologyBetaHcgIndexRoute =
  AuthenticatedPathologyImmunologyBetaHcgIndexRouteImport.update({
    id: '/pathology/immunology/beta-hcg/',
    path: '/pathology/immunology/beta-hcg/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyHematologyReportsIndexRoute =
  AuthenticatedPathologyHematologyReportsIndexRouteImport.update({
    id: '/pathology/hematology/reports/',
    path: '/pathology/hematology/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyHematologyProthomBinTimeFullIndexRoute =
  AuthenticatedPathologyHematologyProthomBinTimeFullIndexRouteImport.update({
    id: '/pathology/hematology/prothom-bin-time-full/',
    path: '/pathology/hematology/prothom-bin-time-full/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyHematologyPeripheralBloodFilmIndexRoute =
  AuthenticatedPathologyHematologyPeripheralBloodFilmIndexRouteImport.update({
    id: '/pathology/hematology/peripheral-blood-film/',
    path: '/pathology/hematology/peripheral-blood-film/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyHematologyCbcShortIndexRoute =
  AuthenticatedPathologyHematologyCbcShortIndexRouteImport.update({
    id: '/pathology/hematology/cbc-short/',
    path: '/pathology/hematology/cbc-short/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyHematologyBloodForTcdcIndexRoute =
  AuthenticatedPathologyHematologyBloodForTcdcIndexRouteImport.update({
    id: '/pathology/hematology/blood-for-tcdc/',
    path: '/pathology/hematology/blood-for-tcdc/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyHematologyBloodForBtCtIndexRoute =
  AuthenticatedPathologyHematologyBloodForBtCtIndexRouteImport.update({
    id: '/pathology/hematology/blood-for-bt-ct/',
    path: '/pathology/hematology/blood-for-bt-ct/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyBiochemicalReportsIndexRoute =
  AuthenticatedPathologyBiochemicalReportsIndexRouteImport.update({
    id: '/pathology/biochemical/reports/',
    path: '/pathology/biochemical/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyBiochemicalLipidProfileIndexRoute =
  AuthenticatedPathologyBiochemicalLipidProfileIndexRouteImport.update({
    id: '/pathology/biochemical/lipid-profile/',
    path: '/pathology/biochemical/lipid-profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedXRayAllReportsEditIdRoute =
  AuthenticatedXRayAllReportsEditIdRouteImport.update({
    id: '/x-ray/all-reports/edit/$id',
    path: '/x-ray/all-reports/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUltrasonogramAllReportsEditIdRoute =
  AuthenticatedUltrasonogramAllReportsEditIdRouteImport.update({
    id: '/ultrasonogram/all-reports/edit/$id',
    path: '/ultrasonogram/all-reports/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcgAllReportsEditIdRoute =
  AuthenticatedEcgAllReportsEditIdRouteImport.update({
    id: '/ecg/all-reports/edit/$id',
    path: '/ecg/all-reports/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyUrineUrineForReFullEditIdRoute =
  AuthenticatedPathologyUrineUrineForReFullEditIdRouteImport.update({
    id: '/pathology/urine/urine-for-re-full/edit/$id',
    path: '/pathology/urine/urine-for-re-full/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyStoolStoolReEditIdRoute =
  AuthenticatedPathologyStoolStoolReEditIdRouteImport.update({
    id: '/pathology/stool/stool-re/edit/$id',
    path: '/pathology/stool/stool-re/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologySpecialSemenEditReportIdRoute =
  AuthenticatedPathologySpecialSemenEditReportIdRouteImport.update({
    id: '/pathology/special/semen/edit/$reportId',
    path: '/pathology/special/semen/edit/$reportId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyHematologyCbcShortEditIdRoute =
  AuthenticatedPathologyHematologyCbcShortEditIdRouteImport.update({
    id: '/pathology/hematology/cbc-short/edit/$id',
    path: '/pathology/hematology/cbc-short/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyBiochemicalReportsEditReportIdRoute =
  AuthenticatedPathologyBiochemicalReportsEditReportIdRouteImport.update({
    id: '/pathology/biochemical/reports/edit/$reportId',
    path: '/pathology/biochemical/reports/edit/$reportId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologySpecialAllHormonesEditIdIndexRoute =
  AuthenticatedPathologySpecialAllHormonesEditIdIndexRouteImport.update({
    id: '/pathology/special/all-hormones/edit/$id/',
    path: '/pathology/special/all-hormones/edit/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyImmunologyReportsEditIdIndexRoute =
  AuthenticatedPathologyImmunologyReportsEditIdIndexRouteImport.update({
    id: '/pathology/immunology/reports/edit/$id/',
    path: '/pathology/immunology/reports/edit/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPathologyHematologyReportsEditIdIndexRoute =
  AuthenticatedPathologyHematologyReportsEditIdIndexRouteImport.update({
    id: '/pathology/hematology/reports/edit/$id/',
    path: '/pathology/hematology/reports/edit/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/departments': typeof AuthenticatedDepartmentsIndexRoute
  '/doctors': typeof AuthenticatedDoctorsIndexRoute
  '/due-collection': typeof AuthenticatedDueCollectionIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/tests': typeof AuthenticatedTestsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/ecg/all-reports': typeof AuthenticatedEcgAllReportsIndexRoute
  '/invoices/create': typeof AuthenticatedInvoicesCreateIndexRoute
  '/invoices/list': typeof AuthenticatedInvoicesListIndexRoute
  '/tests/create': typeof AuthenticatedTestsCreateIndexRoute
  '/ultrasonogram/all-reports': typeof AuthenticatedUltrasonogramAllReportsIndexRoute
  '/x-ray/all-reports': typeof AuthenticatedXRayAllReportsIndexRoute
  '/ecg/all-reports/edit/$id': typeof AuthenticatedEcgAllReportsEditIdRoute
  '/ultrasonogram/all-reports/edit/$id': typeof AuthenticatedUltrasonogramAllReportsEditIdRoute
  '/x-ray/all-reports/edit/$id': typeof AuthenticatedXRayAllReportsEditIdRoute
  '/pathology/biochemical/lipid-profile': typeof AuthenticatedPathologyBiochemicalLipidProfileIndexRoute
  '/pathology/biochemical/reports': typeof AuthenticatedPathologyBiochemicalReportsIndexRoute
  '/pathology/hematology/blood-for-bt-ct': typeof AuthenticatedPathologyHematologyBloodForBtCtIndexRoute
  '/pathology/hematology/blood-for-tcdc': typeof AuthenticatedPathologyHematologyBloodForTcdcIndexRoute
  '/pathology/hematology/cbc-short': typeof AuthenticatedPathologyHematologyCbcShortIndexRoute
  '/pathology/hematology/peripheral-blood-film': typeof AuthenticatedPathologyHematologyPeripheralBloodFilmIndexRoute
  '/pathology/hematology/prothom-bin-time-full': typeof AuthenticatedPathologyHematologyProthomBinTimeFullIndexRoute
  '/pathology/hematology/reports': typeof AuthenticatedPathologyHematologyReportsIndexRoute
  '/pathology/immunology/beta-hcg': typeof AuthenticatedPathologyImmunologyBetaHcgIndexRoute
  '/pathology/immunology/blood-group': typeof AuthenticatedPathologyImmunologyBloodGroupIndexRoute
  '/pathology/immunology/mt': typeof AuthenticatedPathologyImmunologyMtIndexRoute
  '/pathology/immunology/reports': typeof AuthenticatedPathologyImmunologyReportsIndexRoute
  '/pathology/immunology/widal-test': typeof AuthenticatedPathologyImmunologyWidalTestIndexRoute
  '/pathology/special/all-hormones': typeof AuthenticatedPathologySpecialAllHormonesIndexRoute
  '/pathology/special/electrolytes': typeof AuthenticatedPathologySpecialElectrolytesIndexRoute
  '/pathology/special/semen': typeof AuthenticatedPathologySpecialSemenIndexRoute
  '/pathology/special/skin-scrapping-for-fungus': typeof AuthenticatedPathologySpecialSkinScrappingForFungusIndexRoute
  '/pathology/special/sputum': typeof AuthenticatedPathologySpecialSputumIndexRoute
  '/pathology/special/t3t4tsh': typeof AuthenticatedPathologySpecialT3t4tshIndexRoute
  '/pathology/stool/ocult-blood-test': typeof AuthenticatedPathologyStoolOcultBloodTestIndexRoute
  '/pathology/stool/reducing-substance': typeof AuthenticatedPathologyStoolReducingSubstanceIndexRoute
  '/pathology/stool/stool-re': typeof AuthenticatedPathologyStoolStoolReIndexRoute
  '/pathology/urine/urine-for-albumin': typeof AuthenticatedPathologyUrineUrineForAlbuminIndexRoute
  '/pathology/urine/urine-for-re-full': typeof AuthenticatedPathologyUrineUrineForReFullIndexRoute
  '/pathology/urine/urine-for-sugar': typeof AuthenticatedPathologyUrineUrineForSugarIndexRoute
  '/tests/edit/$id': typeof AuthenticatedTestsEditIdIndexRoute
  '/pathology/biochemical/reports/edit/$reportId': typeof AuthenticatedPathologyBiochemicalReportsEditReportIdRoute
  '/pathology/hematology/cbc-short/edit/$id': typeof AuthenticatedPathologyHematologyCbcShortEditIdRoute
  '/pathology/special/semen/edit/$reportId': typeof AuthenticatedPathologySpecialSemenEditReportIdRoute
  '/pathology/stool/stool-re/edit/$id': typeof AuthenticatedPathologyStoolStoolReEditIdRoute
  '/pathology/urine/urine-for-re-full/edit/$id': typeof AuthenticatedPathologyUrineUrineForReFullEditIdRoute
  '/pathology/hematology/reports/edit/$id': typeof AuthenticatedPathologyHematologyReportsEditIdIndexRoute
  '/pathology/immunology/reports/edit/$id': typeof AuthenticatedPathologyImmunologyReportsEditIdIndexRoute
  '/pathology/special/all-hormones/edit/$id': typeof AuthenticatedPathologySpecialAllHormonesEditIdIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/departments': typeof AuthenticatedDepartmentsIndexRoute
  '/doctors': typeof AuthenticatedDoctorsIndexRoute
  '/due-collection': typeof AuthenticatedDueCollectionIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/tests': typeof AuthenticatedTestsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/ecg/all-reports': typeof AuthenticatedEcgAllReportsIndexRoute
  '/invoices/create': typeof AuthenticatedInvoicesCreateIndexRoute
  '/invoices/list': typeof AuthenticatedInvoicesListIndexRoute
  '/tests/create': typeof AuthenticatedTestsCreateIndexRoute
  '/ultrasonogram/all-reports': typeof AuthenticatedUltrasonogramAllReportsIndexRoute
  '/x-ray/all-reports': typeof AuthenticatedXRayAllReportsIndexRoute
  '/ecg/all-reports/edit/$id': typeof AuthenticatedEcgAllReportsEditIdRoute
  '/ultrasonogram/all-reports/edit/$id': typeof AuthenticatedUltrasonogramAllReportsEditIdRoute
  '/x-ray/all-reports/edit/$id': typeof AuthenticatedXRayAllReportsEditIdRoute
  '/pathology/biochemical/lipid-profile': typeof AuthenticatedPathologyBiochemicalLipidProfileIndexRoute
  '/pathology/biochemical/reports': typeof AuthenticatedPathologyBiochemicalReportsIndexRoute
  '/pathology/hematology/blood-for-bt-ct': typeof AuthenticatedPathologyHematologyBloodForBtCtIndexRoute
  '/pathology/hematology/blood-for-tcdc': typeof AuthenticatedPathologyHematologyBloodForTcdcIndexRoute
  '/pathology/hematology/cbc-short': typeof AuthenticatedPathologyHematologyCbcShortIndexRoute
  '/pathology/hematology/peripheral-blood-film': typeof AuthenticatedPathologyHematologyPeripheralBloodFilmIndexRoute
  '/pathology/hematology/prothom-bin-time-full': typeof AuthenticatedPathologyHematologyProthomBinTimeFullIndexRoute
  '/pathology/hematology/reports': typeof AuthenticatedPathologyHematologyReportsIndexRoute
  '/pathology/immunology/beta-hcg': typeof AuthenticatedPathologyImmunologyBetaHcgIndexRoute
  '/pathology/immunology/blood-group': typeof AuthenticatedPathologyImmunologyBloodGroupIndexRoute
  '/pathology/immunology/mt': typeof AuthenticatedPathologyImmunologyMtIndexRoute
  '/pathology/immunology/reports': typeof AuthenticatedPathologyImmunologyReportsIndexRoute
  '/pathology/immunology/widal-test': typeof AuthenticatedPathologyImmunologyWidalTestIndexRoute
  '/pathology/special/all-hormones': typeof AuthenticatedPathologySpecialAllHormonesIndexRoute
  '/pathology/special/electrolytes': typeof AuthenticatedPathologySpecialElectrolytesIndexRoute
  '/pathology/special/semen': typeof AuthenticatedPathologySpecialSemenIndexRoute
  '/pathology/special/skin-scrapping-for-fungus': typeof AuthenticatedPathologySpecialSkinScrappingForFungusIndexRoute
  '/pathology/special/sputum': typeof AuthenticatedPathologySpecialSputumIndexRoute
  '/pathology/special/t3t4tsh': typeof AuthenticatedPathologySpecialT3t4tshIndexRoute
  '/pathology/stool/ocult-blood-test': typeof AuthenticatedPathologyStoolOcultBloodTestIndexRoute
  '/pathology/stool/reducing-substance': typeof AuthenticatedPathologyStoolReducingSubstanceIndexRoute
  '/pathology/stool/stool-re': typeof AuthenticatedPathologyStoolStoolReIndexRoute
  '/pathology/urine/urine-for-albumin': typeof AuthenticatedPathologyUrineUrineForAlbuminIndexRoute
  '/pathology/urine/urine-for-re-full': typeof AuthenticatedPathologyUrineUrineForReFullIndexRoute
  '/pathology/urine/urine-for-sugar': typeof AuthenticatedPathologyUrineUrineForSugarIndexRoute
  '/tests/edit/$id': typeof AuthenticatedTestsEditIdIndexRoute
  '/pathology/biochemical/reports/edit/$reportId': typeof AuthenticatedPathologyBiochemicalReportsEditReportIdRoute
  '/pathology/hematology/cbc-short/edit/$id': typeof AuthenticatedPathologyHematologyCbcShortEditIdRoute
  '/pathology/special/semen/edit/$reportId': typeof AuthenticatedPathologySpecialSemenEditReportIdRoute
  '/pathology/stool/stool-re/edit/$id': typeof AuthenticatedPathologyStoolStoolReEditIdRoute
  '/pathology/urine/urine-for-re-full/edit/$id': typeof AuthenticatedPathologyUrineUrineForReFullEditIdRoute
  '/pathology/hematology/reports/edit/$id': typeof AuthenticatedPathologyHematologyReportsEditIdIndexRoute
  '/pathology/immunology/reports/edit/$id': typeof AuthenticatedPathologyImmunologyReportsEditIdIndexRoute
  '/pathology/special/all-hormones/edit/$id': typeof AuthenticatedPathologySpecialAllHormonesEditIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/departments/': typeof AuthenticatedDepartmentsIndexRoute
  '/_authenticated/doctors/': typeof AuthenticatedDoctorsIndexRoute
  '/_authenticated/due-collection/': typeof AuthenticatedDueCollectionIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/tests/': typeof AuthenticatedTestsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/ecg/all-reports/': typeof AuthenticatedEcgAllReportsIndexRoute
  '/_authenticated/invoices/create/': typeof AuthenticatedInvoicesCreateIndexRoute
  '/_authenticated/invoices/list/': typeof AuthenticatedInvoicesListIndexRoute
  '/_authenticated/tests/create/': typeof AuthenticatedTestsCreateIndexRoute
  '/_authenticated/ultrasonogram/all-reports/': typeof AuthenticatedUltrasonogramAllReportsIndexRoute
  '/_authenticated/x-ray/all-reports/': typeof AuthenticatedXRayAllReportsIndexRoute
  '/_authenticated/ecg/all-reports/edit/$id': typeof AuthenticatedEcgAllReportsEditIdRoute
  '/_authenticated/ultrasonogram/all-reports/edit/$id': typeof AuthenticatedUltrasonogramAllReportsEditIdRoute
  '/_authenticated/x-ray/all-reports/edit/$id': typeof AuthenticatedXRayAllReportsEditIdRoute
  '/_authenticated/pathology/biochemical/lipid-profile/': typeof AuthenticatedPathologyBiochemicalLipidProfileIndexRoute
  '/_authenticated/pathology/biochemical/reports/': typeof AuthenticatedPathologyBiochemicalReportsIndexRoute
  '/_authenticated/pathology/hematology/blood-for-bt-ct/': typeof AuthenticatedPathologyHematologyBloodForBtCtIndexRoute
  '/_authenticated/pathology/hematology/blood-for-tcdc/': typeof AuthenticatedPathologyHematologyBloodForTcdcIndexRoute
  '/_authenticated/pathology/hematology/cbc-short/': typeof AuthenticatedPathologyHematologyCbcShortIndexRoute
  '/_authenticated/pathology/hematology/peripheral-blood-film/': typeof AuthenticatedPathologyHematologyPeripheralBloodFilmIndexRoute
  '/_authenticated/pathology/hematology/prothom-bin-time-full/': typeof AuthenticatedPathologyHematologyProthomBinTimeFullIndexRoute
  '/_authenticated/pathology/hematology/reports/': typeof AuthenticatedPathologyHematologyReportsIndexRoute
  '/_authenticated/pathology/immunology/beta-hcg/': typeof AuthenticatedPathologyImmunologyBetaHcgIndexRoute
  '/_authenticated/pathology/immunology/blood-group/': typeof AuthenticatedPathologyImmunologyBloodGroupIndexRoute
  '/_authenticated/pathology/immunology/mt/': typeof AuthenticatedPathologyImmunologyMtIndexRoute
  '/_authenticated/pathology/immunology/reports/': typeof AuthenticatedPathologyImmunologyReportsIndexRoute
  '/_authenticated/pathology/immunology/widal-test/': typeof AuthenticatedPathologyImmunologyWidalTestIndexRoute
  '/_authenticated/pathology/special/all-hormones/': typeof AuthenticatedPathologySpecialAllHormonesIndexRoute
  '/_authenticated/pathology/special/electrolytes/': typeof AuthenticatedPathologySpecialElectrolytesIndexRoute
  '/_authenticated/pathology/special/semen/': typeof AuthenticatedPathologySpecialSemenIndexRoute
  '/_authenticated/pathology/special/skin-scrapping-for-fungus/': typeof AuthenticatedPathologySpecialSkinScrappingForFungusIndexRoute
  '/_authenticated/pathology/special/sputum/': typeof AuthenticatedPathologySpecialSputumIndexRoute
  '/_authenticated/pathology/special/t3t4tsh/': typeof AuthenticatedPathologySpecialT3t4tshIndexRoute
  '/_authenticated/pathology/stool/ocult-blood-test/': typeof AuthenticatedPathologyStoolOcultBloodTestIndexRoute
  '/_authenticated/pathology/stool/reducing-substance/': typeof AuthenticatedPathologyStoolReducingSubstanceIndexRoute
  '/_authenticated/pathology/stool/stool-re/': typeof AuthenticatedPathologyStoolStoolReIndexRoute
  '/_authenticated/pathology/urine/urine-for-albumin/': typeof AuthenticatedPathologyUrineUrineForAlbuminIndexRoute
  '/_authenticated/pathology/urine/urine-for-re-full/': typeof AuthenticatedPathologyUrineUrineForReFullIndexRoute
  '/_authenticated/pathology/urine/urine-for-sugar/': typeof AuthenticatedPathologyUrineUrineForSugarIndexRoute
  '/_authenticated/tests/edit/$id/': typeof AuthenticatedTestsEditIdIndexRoute
  '/_authenticated/pathology/biochemical/reports/edit/$reportId': typeof AuthenticatedPathologyBiochemicalReportsEditReportIdRoute
  '/_authenticated/pathology/hematology/cbc-short/edit/$id': typeof AuthenticatedPathologyHematologyCbcShortEditIdRoute
  '/_authenticated/pathology/special/semen/edit/$reportId': typeof AuthenticatedPathologySpecialSemenEditReportIdRoute
  '/_authenticated/pathology/stool/stool-re/edit/$id': typeof AuthenticatedPathologyStoolStoolReEditIdRoute
  '/_authenticated/pathology/urine/urine-for-re-full/edit/$id': typeof AuthenticatedPathologyUrineUrineForReFullEditIdRoute
  '/_authenticated/pathology/hematology/reports/edit/$id/': typeof AuthenticatedPathologyHematologyReportsEditIdIndexRoute
  '/_authenticated/pathology/immunology/reports/edit/$id/': typeof AuthenticatedPathologyImmunologyReportsEditIdIndexRoute
  '/_authenticated/pathology/special/all-hormones/edit/$id/': typeof AuthenticatedPathologySpecialAllHormonesEditIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/settings'
    | '/clerk/'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/categories'
    | '/chats'
    | '/departments'
    | '/doctors'
    | '/due-collection'
    | '/help-center'
    | '/services'
    | '/settings/'
    | '/tasks'
    | '/tests'
    | '/users'
    | '/ecg/all-reports'
    | '/invoices/create'
    | '/invoices/list'
    | '/tests/create'
    | '/ultrasonogram/all-reports'
    | '/x-ray/all-reports'
    | '/ecg/all-reports/edit/$id'
    | '/ultrasonogram/all-reports/edit/$id'
    | '/x-ray/all-reports/edit/$id'
    | '/pathology/biochemical/lipid-profile'
    | '/pathology/biochemical/reports'
    | '/pathology/hematology/blood-for-bt-ct'
    | '/pathology/hematology/blood-for-tcdc'
    | '/pathology/hematology/cbc-short'
    | '/pathology/hematology/peripheral-blood-film'
    | '/pathology/hematology/prothom-bin-time-full'
    | '/pathology/hematology/reports'
    | '/pathology/immunology/beta-hcg'
    | '/pathology/immunology/blood-group'
    | '/pathology/immunology/mt'
    | '/pathology/immunology/reports'
    | '/pathology/immunology/widal-test'
    | '/pathology/special/all-hormones'
    | '/pathology/special/electrolytes'
    | '/pathology/special/semen'
    | '/pathology/special/skin-scrapping-for-fungus'
    | '/pathology/special/sputum'
    | '/pathology/special/t3t4tsh'
    | '/pathology/stool/ocult-blood-test'
    | '/pathology/stool/reducing-substance'
    | '/pathology/stool/stool-re'
    | '/pathology/urine/urine-for-albumin'
    | '/pathology/urine/urine-for-re-full'
    | '/pathology/urine/urine-for-sugar'
    | '/tests/edit/$id'
    | '/pathology/biochemical/reports/edit/$reportId'
    | '/pathology/hematology/cbc-short/edit/$id'
    | '/pathology/special/semen/edit/$reportId'
    | '/pathology/stool/stool-re/edit/$id'
    | '/pathology/urine/urine-for-re-full/edit/$id'
    | '/pathology/hematology/reports/edit/$id'
    | '/pathology/immunology/reports/edit/$id'
    | '/pathology/special/all-hormones/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/categories'
    | '/chats'
    | '/departments'
    | '/doctors'
    | '/due-collection'
    | '/help-center'
    | '/services'
    | '/settings'
    | '/tasks'
    | '/tests'
    | '/users'
    | '/ecg/all-reports'
    | '/invoices/create'
    | '/invoices/list'
    | '/tests/create'
    | '/ultrasonogram/all-reports'
    | '/x-ray/all-reports'
    | '/ecg/all-reports/edit/$id'
    | '/ultrasonogram/all-reports/edit/$id'
    | '/x-ray/all-reports/edit/$id'
    | '/pathology/biochemical/lipid-profile'
    | '/pathology/biochemical/reports'
    | '/pathology/hematology/blood-for-bt-ct'
    | '/pathology/hematology/blood-for-tcdc'
    | '/pathology/hematology/cbc-short'
    | '/pathology/hematology/peripheral-blood-film'
    | '/pathology/hematology/prothom-bin-time-full'
    | '/pathology/hematology/reports'
    | '/pathology/immunology/beta-hcg'
    | '/pathology/immunology/blood-group'
    | '/pathology/immunology/mt'
    | '/pathology/immunology/reports'
    | '/pathology/immunology/widal-test'
    | '/pathology/special/all-hormones'
    | '/pathology/special/electrolytes'
    | '/pathology/special/semen'
    | '/pathology/special/skin-scrapping-for-fungus'
    | '/pathology/special/sputum'
    | '/pathology/special/t3t4tsh'
    | '/pathology/stool/ocult-blood-test'
    | '/pathology/stool/reducing-substance'
    | '/pathology/stool/stool-re'
    | '/pathology/urine/urine-for-albumin'
    | '/pathology/urine/urine-for-re-full'
    | '/pathology/urine/urine-for-sugar'
    | '/tests/edit/$id'
    | '/pathology/biochemical/reports/edit/$reportId'
    | '/pathology/hematology/cbc-short/edit/$id'
    | '/pathology/special/semen/edit/$reportId'
    | '/pathology/stool/stool-re/edit/$id'
    | '/pathology/urine/urine-for-re-full/edit/$id'
    | '/pathology/hematology/reports/edit/$id'
    | '/pathology/immunology/reports/edit/$id'
    | '/pathology/special/all-hormones/edit/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/categories/'
    | '/_authenticated/chats/'
    | '/_authenticated/departments/'
    | '/_authenticated/doctors/'
    | '/_authenticated/due-collection/'
    | '/_authenticated/help-center/'
    | '/_authenticated/services/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/tests/'
    | '/_authenticated/users/'
    | '/_authenticated/ecg/all-reports/'
    | '/_authenticated/invoices/create/'
    | '/_authenticated/invoices/list/'
    | '/_authenticated/tests/create/'
    | '/_authenticated/ultrasonogram/all-reports/'
    | '/_authenticated/x-ray/all-reports/'
    | '/_authenticated/ecg/all-reports/edit/$id'
    | '/_authenticated/ultrasonogram/all-reports/edit/$id'
    | '/_authenticated/x-ray/all-reports/edit/$id'
    | '/_authenticated/pathology/biochemical/lipid-profile/'
    | '/_authenticated/pathology/biochemical/reports/'
    | '/_authenticated/pathology/hematology/blood-for-bt-ct/'
    | '/_authenticated/pathology/hematology/blood-for-tcdc/'
    | '/_authenticated/pathology/hematology/cbc-short/'
    | '/_authenticated/pathology/hematology/peripheral-blood-film/'
    | '/_authenticated/pathology/hematology/prothom-bin-time-full/'
    | '/_authenticated/pathology/hematology/reports/'
    | '/_authenticated/pathology/immunology/beta-hcg/'
    | '/_authenticated/pathology/immunology/blood-group/'
    | '/_authenticated/pathology/immunology/mt/'
    | '/_authenticated/pathology/immunology/reports/'
    | '/_authenticated/pathology/immunology/widal-test/'
    | '/_authenticated/pathology/special/all-hormones/'
    | '/_authenticated/pathology/special/electrolytes/'
    | '/_authenticated/pathology/special/semen/'
    | '/_authenticated/pathology/special/skin-scrapping-for-fungus/'
    | '/_authenticated/pathology/special/sputum/'
    | '/_authenticated/pathology/special/t3t4tsh/'
    | '/_authenticated/pathology/stool/ocult-blood-test/'
    | '/_authenticated/pathology/stool/reducing-substance/'
    | '/_authenticated/pathology/stool/stool-re/'
    | '/_authenticated/pathology/urine/urine-for-albumin/'
    | '/_authenticated/pathology/urine/urine-for-re-full/'
    | '/_authenticated/pathology/urine/urine-for-sugar/'
    | '/_authenticated/tests/edit/$id/'
    | '/_authenticated/pathology/biochemical/reports/edit/$reportId'
    | '/_authenticated/pathology/hematology/cbc-short/edit/$id'
    | '/_authenticated/pathology/special/semen/edit/$reportId'
    | '/_authenticated/pathology/stool/stool-re/edit/$id'
    | '/_authenticated/pathology/urine/urine-for-re-full/edit/$id'
    | '/_authenticated/pathology/hematology/reports/edit/$id/'
    | '/_authenticated/pathology/immunology/reports/edit/$id/'
    | '/_authenticated/pathology/special/all-hormones/edit/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: '/'
      fullPath: '/clerk/'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/': {
      id: '/_authenticated/tests/'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof AuthenticatedTestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/due-collection/': {
      id: '/_authenticated/due-collection/'
      path: '/due-collection'
      fullPath: '/due-collection'
      preLoaderRoute: typeof AuthenticatedDueCollectionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctors/': {
      id: '/_authenticated/doctors/'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedDoctorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments/': {
      id: '/_authenticated/departments/'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/x-ray/all-reports/': {
      id: '/_authenticated/x-ray/all-reports/'
      path: '/x-ray/all-reports'
      fullPath: '/x-ray/all-reports'
      preLoaderRoute: typeof AuthenticatedXRayAllReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ultrasonogram/all-reports/': {
      id: '/_authenticated/ultrasonogram/all-reports/'
      path: '/ultrasonogram/all-reports'
      fullPath: '/ultrasonogram/all-reports'
      preLoaderRoute: typeof AuthenticatedUltrasonogramAllReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/create/': {
      id: '/_authenticated/tests/create/'
      path: '/tests/create'
      fullPath: '/tests/create'
      preLoaderRoute: typeof AuthenticatedTestsCreateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/list/': {
      id: '/_authenticated/invoices/list/'
      path: '/invoices/list'
      fullPath: '/invoices/list'
      preLoaderRoute: typeof AuthenticatedInvoicesListIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/create/': {
      id: '/_authenticated/invoices/create/'
      path: '/invoices/create'
      fullPath: '/invoices/create'
      preLoaderRoute: typeof AuthenticatedInvoicesCreateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecg/all-reports/': {
      id: '/_authenticated/ecg/all-reports/'
      path: '/ecg/all-reports'
      fullPath: '/ecg/all-reports'
      preLoaderRoute: typeof AuthenticatedEcgAllReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/edit/$id/': {
      id: '/_authenticated/tests/edit/$id/'
      path: '/tests/edit/$id'
      fullPath: '/tests/edit/$id'
      preLoaderRoute: typeof AuthenticatedTestsEditIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/urine/urine-for-sugar/': {
      id: '/_authenticated/pathology/urine/urine-for-sugar/'
      path: '/pathology/urine/urine-for-sugar'
      fullPath: '/pathology/urine/urine-for-sugar'
      preLoaderRoute: typeof AuthenticatedPathologyUrineUrineForSugarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/urine/urine-for-re-full/': {
      id: '/_authenticated/pathology/urine/urine-for-re-full/'
      path: '/pathology/urine/urine-for-re-full'
      fullPath: '/pathology/urine/urine-for-re-full'
      preLoaderRoute: typeof AuthenticatedPathologyUrineUrineForReFullIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/urine/urine-for-albumin/': {
      id: '/_authenticated/pathology/urine/urine-for-albumin/'
      path: '/pathology/urine/urine-for-albumin'
      fullPath: '/pathology/urine/urine-for-albumin'
      preLoaderRoute: typeof AuthenticatedPathologyUrineUrineForAlbuminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/stool/stool-re/': {
      id: '/_authenticated/pathology/stool/stool-re/'
      path: '/pathology/stool/stool-re'
      fullPath: '/pathology/stool/stool-re'
      preLoaderRoute: typeof AuthenticatedPathologyStoolStoolReIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/stool/reducing-substance/': {
      id: '/_authenticated/pathology/stool/reducing-substance/'
      path: '/pathology/stool/reducing-substance'
      fullPath: '/pathology/stool/reducing-substance'
      preLoaderRoute: typeof AuthenticatedPathologyStoolReducingSubstanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/stool/ocult-blood-test/': {
      id: '/_authenticated/pathology/stool/ocult-blood-test/'
      path: '/pathology/stool/ocult-blood-test'
      fullPath: '/pathology/stool/ocult-blood-test'
      preLoaderRoute: typeof AuthenticatedPathologyStoolOcultBloodTestIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/special/t3t4tsh/': {
      id: '/_authenticated/pathology/special/t3t4tsh/'
      path: '/pathology/special/t3t4tsh'
      fullPath: '/pathology/special/t3t4tsh'
      preLoaderRoute: typeof AuthenticatedPathologySpecialT3t4tshIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/special/sputum/': {
      id: '/_authenticated/pathology/special/sputum/'
      path: '/pathology/special/sputum'
      fullPath: '/pathology/special/sputum'
      preLoaderRoute: typeof AuthenticatedPathologySpecialSputumIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/special/skin-scrapping-for-fungus/': {
      id: '/_authenticated/pathology/special/skin-scrapping-for-fungus/'
      path: '/pathology/special/skin-scrapping-for-fungus'
      fullPath: '/pathology/special/skin-scrapping-for-fungus'
      preLoaderRoute: typeof AuthenticatedPathologySpecialSkinScrappingForFungusIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/special/semen/': {
      id: '/_authenticated/pathology/special/semen/'
      path: '/pathology/special/semen'
      fullPath: '/pathology/special/semen'
      preLoaderRoute: typeof AuthenticatedPathologySpecialSemenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/special/electrolytes/': {
      id: '/_authenticated/pathology/special/electrolytes/'
      path: '/pathology/special/electrolytes'
      fullPath: '/pathology/special/electrolytes'
      preLoaderRoute: typeof AuthenticatedPathologySpecialElectrolytesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/special/all-hormones/': {
      id: '/_authenticated/pathology/special/all-hormones/'
      path: '/pathology/special/all-hormones'
      fullPath: '/pathology/special/all-hormones'
      preLoaderRoute: typeof AuthenticatedPathologySpecialAllHormonesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/immunology/widal-test/': {
      id: '/_authenticated/pathology/immunology/widal-test/'
      path: '/pathology/immunology/widal-test'
      fullPath: '/pathology/immunology/widal-test'
      preLoaderRoute: typeof AuthenticatedPathologyImmunologyWidalTestIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/immunology/reports/': {
      id: '/_authenticated/pathology/immunology/reports/'
      path: '/pathology/immunology/reports'
      fullPath: '/pathology/immunology/reports'
      preLoaderRoute: typeof AuthenticatedPathologyImmunologyReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/immunology/mt/': {
      id: '/_authenticated/pathology/immunology/mt/'
      path: '/pathology/immunology/mt'
      fullPath: '/pathology/immunology/mt'
      preLoaderRoute: typeof AuthenticatedPathologyImmunologyMtIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/immunology/blood-group/': {
      id: '/_authenticated/pathology/immunology/blood-group/'
      path: '/pathology/immunology/blood-group'
      fullPath: '/pathology/immunology/blood-group'
      preLoaderRoute: typeof AuthenticatedPathologyImmunologyBloodGroupIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/immunology/beta-hcg/': {
      id: '/_authenticated/pathology/immunology/beta-hcg/'
      path: '/pathology/immunology/beta-hcg'
      fullPath: '/pathology/immunology/beta-hcg'
      preLoaderRoute: typeof AuthenticatedPathologyImmunologyBetaHcgIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/hematology/reports/': {
      id: '/_authenticated/pathology/hematology/reports/'
      path: '/pathology/hematology/reports'
      fullPath: '/pathology/hematology/reports'
      preLoaderRoute: typeof AuthenticatedPathologyHematologyReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/hematology/prothom-bin-time-full/': {
      id: '/_authenticated/pathology/hematology/prothom-bin-time-full/'
      path: '/pathology/hematology/prothom-bin-time-full'
      fullPath: '/pathology/hematology/prothom-bin-time-full'
      preLoaderRoute: typeof AuthenticatedPathologyHematologyProthomBinTimeFullIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/hematology/peripheral-blood-film/': {
      id: '/_authenticated/pathology/hematology/peripheral-blood-film/'
      path: '/pathology/hematology/peripheral-blood-film'
      fullPath: '/pathology/hematology/peripheral-blood-film'
      preLoaderRoute: typeof AuthenticatedPathologyHematologyPeripheralBloodFilmIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/hematology/cbc-short/': {
      id: '/_authenticated/pathology/hematology/cbc-short/'
      path: '/pathology/hematology/cbc-short'
      fullPath: '/pathology/hematology/cbc-short'
      preLoaderRoute: typeof AuthenticatedPathologyHematologyCbcShortIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/hematology/blood-for-tcdc/': {
      id: '/_authenticated/pathology/hematology/blood-for-tcdc/'
      path: '/pathology/hematology/blood-for-tcdc'
      fullPath: '/pathology/hematology/blood-for-tcdc'
      preLoaderRoute: typeof AuthenticatedPathologyHematologyBloodForTcdcIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/hematology/blood-for-bt-ct/': {
      id: '/_authenticated/pathology/hematology/blood-for-bt-ct/'
      path: '/pathology/hematology/blood-for-bt-ct'
      fullPath: '/pathology/hematology/blood-for-bt-ct'
      preLoaderRoute: typeof AuthenticatedPathologyHematologyBloodForBtCtIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/biochemical/reports/': {
      id: '/_authenticated/pathology/biochemical/reports/'
      path: '/pathology/biochemical/reports'
      fullPath: '/pathology/biochemical/reports'
      preLoaderRoute: typeof AuthenticatedPathologyBiochemicalReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/biochemical/lipid-profile/': {
      id: '/_authenticated/pathology/biochemical/lipid-profile/'
      path: '/pathology/biochemical/lipid-profile'
      fullPath: '/pathology/biochemical/lipid-profile'
      preLoaderRoute: typeof AuthenticatedPathologyBiochemicalLipidProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/x-ray/all-reports/edit/$id': {
      id: '/_authenticated/x-ray/all-reports/edit/$id'
      path: '/x-ray/all-reports/edit/$id'
      fullPath: '/x-ray/all-reports/edit/$id'
      preLoaderRoute: typeof AuthenticatedXRayAllReportsEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ultrasonogram/all-reports/edit/$id': {
      id: '/_authenticated/ultrasonogram/all-reports/edit/$id'
      path: '/ultrasonogram/all-reports/edit/$id'
      fullPath: '/ultrasonogram/all-reports/edit/$id'
      preLoaderRoute: typeof AuthenticatedUltrasonogramAllReportsEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecg/all-reports/edit/$id': {
      id: '/_authenticated/ecg/all-reports/edit/$id'
      path: '/ecg/all-reports/edit/$id'
      fullPath: '/ecg/all-reports/edit/$id'
      preLoaderRoute: typeof AuthenticatedEcgAllReportsEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/urine/urine-for-re-full/edit/$id': {
      id: '/_authenticated/pathology/urine/urine-for-re-full/edit/$id'
      path: '/pathology/urine/urine-for-re-full/edit/$id'
      fullPath: '/pathology/urine/urine-for-re-full/edit/$id'
      preLoaderRoute: typeof AuthenticatedPathologyUrineUrineForReFullEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/stool/stool-re/edit/$id': {
      id: '/_authenticated/pathology/stool/stool-re/edit/$id'
      path: '/pathology/stool/stool-re/edit/$id'
      fullPath: '/pathology/stool/stool-re/edit/$id'
      preLoaderRoute: typeof AuthenticatedPathologyStoolStoolReEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/special/semen/edit/$reportId': {
      id: '/_authenticated/pathology/special/semen/edit/$reportId'
      path: '/pathology/special/semen/edit/$reportId'
      fullPath: '/pathology/special/semen/edit/$reportId'
      preLoaderRoute: typeof AuthenticatedPathologySpecialSemenEditReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/hematology/cbc-short/edit/$id': {
      id: '/_authenticated/pathology/hematology/cbc-short/edit/$id'
      path: '/pathology/hematology/cbc-short/edit/$id'
      fullPath: '/pathology/hematology/cbc-short/edit/$id'
      preLoaderRoute: typeof AuthenticatedPathologyHematologyCbcShortEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/biochemical/reports/edit/$reportId': {
      id: '/_authenticated/pathology/biochemical/reports/edit/$reportId'
      path: '/pathology/biochemical/reports/edit/$reportId'
      fullPath: '/pathology/biochemical/reports/edit/$reportId'
      preLoaderRoute: typeof AuthenticatedPathologyBiochemicalReportsEditReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/special/all-hormones/edit/$id/': {
      id: '/_authenticated/pathology/special/all-hormones/edit/$id/'
      path: '/pathology/special/all-hormones/edit/$id'
      fullPath: '/pathology/special/all-hormones/edit/$id'
      preLoaderRoute: typeof AuthenticatedPathologySpecialAllHormonesEditIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/immunology/reports/edit/$id/': {
      id: '/_authenticated/pathology/immunology/reports/edit/$id/'
      path: '/pathology/immunology/reports/edit/$id'
      fullPath: '/pathology/immunology/reports/edit/$id'
      preLoaderRoute: typeof AuthenticatedPathologyImmunologyReportsEditIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pathology/hematology/reports/edit/$id/': {
      id: '/_authenticated/pathology/hematology/reports/edit/$id/'
      path: '/pathology/hematology/reports/edit/$id'
      fullPath: '/pathology/hematology/reports/edit/$id'
      preLoaderRoute: typeof AuthenticatedPathologyHematologyReportsEditIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedDepartmentsIndexRoute: typeof AuthenticatedDepartmentsIndexRoute
  AuthenticatedDoctorsIndexRoute: typeof AuthenticatedDoctorsIndexRoute
  AuthenticatedDueCollectionIndexRoute: typeof AuthenticatedDueCollectionIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTestsIndexRoute: typeof AuthenticatedTestsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedEcgAllReportsIndexRoute: typeof AuthenticatedEcgAllReportsIndexRoute
  AuthenticatedInvoicesCreateIndexRoute: typeof AuthenticatedInvoicesCreateIndexRoute
  AuthenticatedInvoicesListIndexRoute: typeof AuthenticatedInvoicesListIndexRoute
  AuthenticatedTestsCreateIndexRoute: typeof AuthenticatedTestsCreateIndexRoute
  AuthenticatedUltrasonogramAllReportsIndexRoute: typeof AuthenticatedUltrasonogramAllReportsIndexRoute
  AuthenticatedXRayAllReportsIndexRoute: typeof AuthenticatedXRayAllReportsIndexRoute
  AuthenticatedEcgAllReportsEditIdRoute: typeof AuthenticatedEcgAllReportsEditIdRoute
  AuthenticatedUltrasonogramAllReportsEditIdRoute: typeof AuthenticatedUltrasonogramAllReportsEditIdRoute
  AuthenticatedXRayAllReportsEditIdRoute: typeof AuthenticatedXRayAllReportsEditIdRoute
  AuthenticatedPathologyBiochemicalLipidProfileIndexRoute: typeof AuthenticatedPathologyBiochemicalLipidProfileIndexRoute
  AuthenticatedPathologyBiochemicalReportsIndexRoute: typeof AuthenticatedPathologyBiochemicalReportsIndexRoute
  AuthenticatedPathologyHematologyBloodForBtCtIndexRoute: typeof AuthenticatedPathologyHematologyBloodForBtCtIndexRoute
  AuthenticatedPathologyHematologyBloodForTcdcIndexRoute: typeof AuthenticatedPathologyHematologyBloodForTcdcIndexRoute
  AuthenticatedPathologyHematologyCbcShortIndexRoute: typeof AuthenticatedPathologyHematologyCbcShortIndexRoute
  AuthenticatedPathologyHematologyPeripheralBloodFilmIndexRoute: typeof AuthenticatedPathologyHematologyPeripheralBloodFilmIndexRoute
  AuthenticatedPathologyHematologyProthomBinTimeFullIndexRoute: typeof AuthenticatedPathologyHematologyProthomBinTimeFullIndexRoute
  AuthenticatedPathologyHematologyReportsIndexRoute: typeof AuthenticatedPathologyHematologyReportsIndexRoute
  AuthenticatedPathologyImmunologyBetaHcgIndexRoute: typeof AuthenticatedPathologyImmunologyBetaHcgIndexRoute
  AuthenticatedPathologyImmunologyBloodGroupIndexRoute: typeof AuthenticatedPathologyImmunologyBloodGroupIndexRoute
  AuthenticatedPathologyImmunologyMtIndexRoute: typeof AuthenticatedPathologyImmunologyMtIndexRoute
  AuthenticatedPathologyImmunologyReportsIndexRoute: typeof AuthenticatedPathologyImmunologyReportsIndexRoute
  AuthenticatedPathologyImmunologyWidalTestIndexRoute: typeof AuthenticatedPathologyImmunologyWidalTestIndexRoute
  AuthenticatedPathologySpecialAllHormonesIndexRoute: typeof AuthenticatedPathologySpecialAllHormonesIndexRoute
  AuthenticatedPathologySpecialElectrolytesIndexRoute: typeof AuthenticatedPathologySpecialElectrolytesIndexRoute
  AuthenticatedPathologySpecialSemenIndexRoute: typeof AuthenticatedPathologySpecialSemenIndexRoute
  AuthenticatedPathologySpecialSkinScrappingForFungusIndexRoute: typeof AuthenticatedPathologySpecialSkinScrappingForFungusIndexRoute
  AuthenticatedPathologySpecialSputumIndexRoute: typeof AuthenticatedPathologySpecialSputumIndexRoute
  AuthenticatedPathologySpecialT3t4tshIndexRoute: typeof AuthenticatedPathologySpecialT3t4tshIndexRoute
  AuthenticatedPathologyStoolOcultBloodTestIndexRoute: typeof AuthenticatedPathologyStoolOcultBloodTestIndexRoute
  AuthenticatedPathologyStoolReducingSubstanceIndexRoute: typeof AuthenticatedPathologyStoolReducingSubstanceIndexRoute
  AuthenticatedPathologyStoolStoolReIndexRoute: typeof AuthenticatedPathologyStoolStoolReIndexRoute
  AuthenticatedPathologyUrineUrineForAlbuminIndexRoute: typeof AuthenticatedPathologyUrineUrineForAlbuminIndexRoute
  AuthenticatedPathologyUrineUrineForReFullIndexRoute: typeof AuthenticatedPathologyUrineUrineForReFullIndexRoute
  AuthenticatedPathologyUrineUrineForSugarIndexRoute: typeof AuthenticatedPathologyUrineUrineForSugarIndexRoute
  AuthenticatedTestsEditIdIndexRoute: typeof AuthenticatedTestsEditIdIndexRoute
  AuthenticatedPathologyBiochemicalReportsEditReportIdRoute: typeof AuthenticatedPathologyBiochemicalReportsEditReportIdRoute
  AuthenticatedPathologyHematologyCbcShortEditIdRoute: typeof AuthenticatedPathologyHematologyCbcShortEditIdRoute
  AuthenticatedPathologySpecialSemenEditReportIdRoute: typeof AuthenticatedPathologySpecialSemenEditReportIdRoute
  AuthenticatedPathologyStoolStoolReEditIdRoute: typeof AuthenticatedPathologyStoolStoolReEditIdRoute
  AuthenticatedPathologyUrineUrineForReFullEditIdRoute: typeof AuthenticatedPathologyUrineUrineForReFullEditIdRoute
  AuthenticatedPathologyHematologyReportsEditIdIndexRoute: typeof AuthenticatedPathologyHematologyReportsEditIdIndexRoute
  AuthenticatedPathologyImmunologyReportsEditIdIndexRoute: typeof AuthenticatedPathologyImmunologyReportsEditIdIndexRoute
  AuthenticatedPathologySpecialAllHormonesEditIdIndexRoute: typeof AuthenticatedPathologySpecialAllHormonesEditIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedDepartmentsIndexRoute: AuthenticatedDepartmentsIndexRoute,
  AuthenticatedDoctorsIndexRoute: AuthenticatedDoctorsIndexRoute,
  AuthenticatedDueCollectionIndexRoute: AuthenticatedDueCollectionIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTestsIndexRoute: AuthenticatedTestsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedEcgAllReportsIndexRoute: AuthenticatedEcgAllReportsIndexRoute,
  AuthenticatedInvoicesCreateIndexRoute: AuthenticatedInvoicesCreateIndexRoute,
  AuthenticatedInvoicesListIndexRoute: AuthenticatedInvoicesListIndexRoute,
  AuthenticatedTestsCreateIndexRoute: AuthenticatedTestsCreateIndexRoute,
  AuthenticatedUltrasonogramAllReportsIndexRoute:
    AuthenticatedUltrasonogramAllReportsIndexRoute,
  AuthenticatedXRayAllReportsIndexRoute: AuthenticatedXRayAllReportsIndexRoute,
  AuthenticatedEcgAllReportsEditIdRoute: AuthenticatedEcgAllReportsEditIdRoute,
  AuthenticatedUltrasonogramAllReportsEditIdRoute:
    AuthenticatedUltrasonogramAllReportsEditIdRoute,
  AuthenticatedXRayAllReportsEditIdRoute:
    AuthenticatedXRayAllReportsEditIdRoute,
  AuthenticatedPathologyBiochemicalLipidProfileIndexRoute:
    AuthenticatedPathologyBiochemicalLipidProfileIndexRoute,
  AuthenticatedPathologyBiochemicalReportsIndexRoute:
    AuthenticatedPathologyBiochemicalReportsIndexRoute,
  AuthenticatedPathologyHematologyBloodForBtCtIndexRoute:
    AuthenticatedPathologyHematologyBloodForBtCtIndexRoute,
  AuthenticatedPathologyHematologyBloodForTcdcIndexRoute:
    AuthenticatedPathologyHematologyBloodForTcdcIndexRoute,
  AuthenticatedPathologyHematologyCbcShortIndexRoute:
    AuthenticatedPathologyHematologyCbcShortIndexRoute,
  AuthenticatedPathologyHematologyPeripheralBloodFilmIndexRoute:
    AuthenticatedPathologyHematologyPeripheralBloodFilmIndexRoute,
  AuthenticatedPathologyHematologyProthomBinTimeFullIndexRoute:
    AuthenticatedPathologyHematologyProthomBinTimeFullIndexRoute,
  AuthenticatedPathologyHematologyReportsIndexRoute:
    AuthenticatedPathologyHematologyReportsIndexRoute,
  AuthenticatedPathologyImmunologyBetaHcgIndexRoute:
    AuthenticatedPathologyImmunologyBetaHcgIndexRoute,
  AuthenticatedPathologyImmunologyBloodGroupIndexRoute:
    AuthenticatedPathologyImmunologyBloodGroupIndexRoute,
  AuthenticatedPathologyImmunologyMtIndexRoute:
    AuthenticatedPathologyImmunologyMtIndexRoute,
  AuthenticatedPathologyImmunologyReportsIndexRoute:
    AuthenticatedPathologyImmunologyReportsIndexRoute,
  AuthenticatedPathologyImmunologyWidalTestIndexRoute:
    AuthenticatedPathologyImmunologyWidalTestIndexRoute,
  AuthenticatedPathologySpecialAllHormonesIndexRoute:
    AuthenticatedPathologySpecialAllHormonesIndexRoute,
  AuthenticatedPathologySpecialElectrolytesIndexRoute:
    AuthenticatedPathologySpecialElectrolytesIndexRoute,
  AuthenticatedPathologySpecialSemenIndexRoute:
    AuthenticatedPathologySpecialSemenIndexRoute,
  AuthenticatedPathologySpecialSkinScrappingForFungusIndexRoute:
    AuthenticatedPathologySpecialSkinScrappingForFungusIndexRoute,
  AuthenticatedPathologySpecialSputumIndexRoute:
    AuthenticatedPathologySpecialSputumIndexRoute,
  AuthenticatedPathologySpecialT3t4tshIndexRoute:
    AuthenticatedPathologySpecialT3t4tshIndexRoute,
  AuthenticatedPathologyStoolOcultBloodTestIndexRoute:
    AuthenticatedPathologyStoolOcultBloodTestIndexRoute,
  AuthenticatedPathologyStoolReducingSubstanceIndexRoute:
    AuthenticatedPathologyStoolReducingSubstanceIndexRoute,
  AuthenticatedPathologyStoolStoolReIndexRoute:
    AuthenticatedPathologyStoolStoolReIndexRoute,
  AuthenticatedPathologyUrineUrineForAlbuminIndexRoute:
    AuthenticatedPathologyUrineUrineForAlbuminIndexRoute,
  AuthenticatedPathologyUrineUrineForReFullIndexRoute:
    AuthenticatedPathologyUrineUrineForReFullIndexRoute,
  AuthenticatedPathologyUrineUrineForSugarIndexRoute:
    AuthenticatedPathologyUrineUrineForSugarIndexRoute,
  AuthenticatedTestsEditIdIndexRoute: AuthenticatedTestsEditIdIndexRoute,
  AuthenticatedPathologyBiochemicalReportsEditReportIdRoute:
    AuthenticatedPathologyBiochemicalReportsEditReportIdRoute,
  AuthenticatedPathologyHematologyCbcShortEditIdRoute:
    AuthenticatedPathologyHematologyCbcShortEditIdRoute,
  AuthenticatedPathologySpecialSemenEditReportIdRoute:
    AuthenticatedPathologySpecialSemenEditReportIdRoute,
  AuthenticatedPathologyStoolStoolReEditIdRoute:
    AuthenticatedPathologyStoolStoolReEditIdRoute,
  AuthenticatedPathologyUrineUrineForReFullEditIdRoute:
    AuthenticatedPathologyUrineUrineForReFullEditIdRoute,
  AuthenticatedPathologyHematologyReportsEditIdIndexRoute:
    AuthenticatedPathologyHematologyReportsEditIdIndexRoute,
  AuthenticatedPathologyImmunologyReportsEditIdIndexRoute:
    AuthenticatedPathologyImmunologyReportsEditIdIndexRoute,
  AuthenticatedPathologySpecialAllHormonesEditIdIndexRoute:
    AuthenticatedPathologySpecialAllHormonesEditIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
